### ISSUE TITLE
Ork Big Shoota errors

### ISSUE THREAD

**Issue by ElBrak** [BSData/wh40k-shadow-war-armageddon#40]
The red dot upgrade is 20 points when it should be 15 and it should not be able to take a scope.

**Comment by GenWilhelm** [comment]
This was fixed in aaf84f134296cd45db09f2c0ffa89e6af5595205 - update your data.

**Comment by ElBrak** [comment]
I manually updated it just now and the values for the big shoota are still wrong.

![reddotsightorks](https://cloud.githubusercontent.com/assets/27624504/25074530/04e8e43e-22b2-11e7-857d-a6c82057e2ae.jpg)
